### ISSUE TITLE
mini.hipatterns: support for hex alpha component and shortcuts

### ISSUE THREAD

**Issue by antonk52** [echasnovski/mini.nvim#374]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.hipatterns

### Description

It would be great if there was a builtin support for hex shortcuts and alpha component. You can see an example below where I list 4 different ways of defining a red color. 

```css
body {
  color: #ff0000; /* the only one that currently supported */
  color: #f00;
  color: #ff000000;
  color: #f000;
}
```

[MDN documentation about HEX](https://developer.mozilla.org/en-US/docs/Web/CSS/hex-color)

Other plugins that support hex shortcut and alpha channels:
- [ccc.nvim](https://github.com/uga-rosa/ccc.nvim)
- [nvim-colorizer.lua](https://github.com/NvChad/nvim-colorizer.lua)

PS: thank you for your work!
